version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db-game
    environment: 
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: Game123
        POSTGRES_DB: GameApp
    ports:
        - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data
    networks:
        - game-network
volumes:
    postgres_data:
networks:
    game-network:
        driver: bridge    
    